Repository Evarisk/digiquali, pull requests merged in 2023-08, with the labels that each got.

#1447 #1443 [Control] fix: send files in mail
  view/control/control_card.php
Labels: Bug, 3

#1446 #1439 [Control] add: public survey link
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 2

#1445 #1438 [Question] fix: massaction lock fatal
  view/question/question_list.php
Labels: Bug, 1

#1453 #1448 [Control] fix: public history bugs
  class/actions_digiquali.class.php
  public/control/public_control_history.php
Labels: Bug, 1

#1450 #1449 [Hook] fix: remove globalcard
  class/actions_digiquali.class.php
  core/modules/modDigiQuali.class.php
Labels: Bug, 1

#1459 #1454 #1457 [Control] fix: trad verdict and more info verdict
  class/control.class.php
  class/question.class.php
  class/sheet.class.php
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Bug, 1

#1460 #1456 #1458 [PublicControl] add: rework IHM public control
  admin/control.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_public_control.tpl.php
  public/control/public_control.php
Labels: Enhancement, 2

#1461 #1455 [Control] fix: next control wrong info
  core/tpl/digiquali_control_list.tpl.php
Labels: Bug, 0

#1464 #1463 [PublicControl] add: improve IHM public control
  core/tpl/digiquali_public_control.tpl.php
Labels: Enhancement, 1

#1466 #1465 [PublicControl] fix: missing check $object->next_control_date
  core/tpl/digiquali_public_control.tpl.php
Labels: Bug, 1

#1469 #1467 [Public] fix: fatal access with multicompany and not login
  class/actions_digiquali.class.php
  class/control.class.php
  core/modules/modDigiQuali.class.php
  public/control/public_control.php
  public/control/public_control_history.php
  public/control/public_survey.php
  view/control/control_card.php
Labels: Bug, 2

#1470 #1468 [PublicControl] add: more picto info verdictObject
  core/tpl/digiquali_public_control.tpl.php
Labels: Enhancement, 1

#1472 #1471 [PublicControl] fix: move parameter in function getNomUrl
  core/tpl/digiquali_public_control.tpl.php
Labels: Bug, 0

#1486 #1462 [TPL] add: show image on public interface
  core/tpl/digiquali_public_control.tpl.php
Labels: Enhancement, 2

#1490 #1489 [Class] fix: remove typage on $ismultientitymanaged
  class/answer.class.php
  class/control.class.php
  class/digiqualidocuments/controldocument.class.php
  class/dolibarrobject.class.php
  class/dolibarrobjects/digiqualisupplierproposal.class.php
  class/question.class.php
  class/sheet.class.php
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 1

#1505 #1504 [Core] add: new version number 1.8.1
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0

#1488 #1487 [Control] add: getNomUrl question on control
  core/tpl/digiquali_control_answers.tpl.php
  public/control/public_control_history.php
  public/control/public_survey.php
Labels: Enhancement, 1

#1512 #1485 #1509 [PublicControl] add: responsive view and fix inconsistency
  class/actions_digiquali.class.php
  core/tpl/digiquali_control_list.tpl.php
  core/tpl/digiquali_public_control.tpl.php
  langs/fr_FR/digiquali.lang
  public/control/public_control_history.php
Labels: Enhancement, 3

#1498 #1482 [Cron] add: cron tab sendEmailsReminder
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 3

#1503 #1499 [Hook] add: Picto for extrafields
  class/actions_digiquali.class.php
  core/modules/modDigiQuali.class.php
  lib/digiquali_sheet.lib.php
Labels: Enhancement, 2

#1514 #1513 [Control] add: manage control date
  class/control.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 2

#1515 #1506 [Control] add: change check status photo medias
  view/control/control_card.php
Labels: Enhancement, 0

#1519 #1518 [IHM] add; control info responsive
  class/actions_digiquali.class.php
  css/digiquali.min.css
  css/scss/page/_control.scss
  css/scss/variable/_colors.scss
  css/scss/variable/_variable.scss
  view/control/control_card.php
Labels: Enhancement, 2

#1522 #1520 [Control] fix: disable confirm validate in save action
  js/digiquali.min.js
  js/modules/control.js
  view/control/control_card.php
Labels: Bug, 1

#1526 #1525 [Control] add: IHM save button
  js/digiquali.min.js
  js/modules/control.js
  view/control/control_card.php
Labels: Enhancement, 1, IHM
