Repository Evarisk/digiquali, pull requests merged in 2023-04, with the labels that each got.

#871 #417 [Sheet] add: remove backtopage and control button on sheet card
  langs/fr_FR/dolismq.lang
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#874 #488 [Mod] add: more element control linked
  admin/sheet.php
  class/control.class.php
  core/modules/modDoliSMQ.class.php
  core/tpl/dolismq_control_list.tpl.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
  view/control/control_card.php
  view/control/control_list.php
  view/sheet/sheet_card.php
Labels: Enhancement, 3

#867 #583 [SQL] add: missing unique key on SQL object key
  sql/control/llx_dolismq_control.key.sql
  sql/control/llx_dolismq_control_extrafields.key.sql
  sql/control/llx_dolismq_controldet.key.sql
  sql/control/llx_dolismq_controldet_extrafields.key.sql
  sql/question/llx_dolismq_question.key.sql
  sql/question/llx_dolismq_question_extrafields.key.sql
  sql/sheet/llx_dolismq_sheet.key.sql
  sql/sheet/llx_dolismq_sheet_extrafields.key.sql
  sql/update.sql
Labels: Enhancement, 2

#868 #464 [Control] add: set STATUS_ARCHIVED action
  class/control.class.php
  class/sheet.class.php
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#892 #883 #886 [IHM] fix: ihm button on control card
  view/control/control_card.php
Labels: Enhancement, 2, IHM

#891 #802 [ODT] add: new odt model
  class/dolismqdocuments.class.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  documents/doctemplates/controldocument/template_controldocument_v_photo.odt
Labels: Enhancement, 3, ODT / PDF

#894 #827 #856 #876 [Question] fix: answer lock, triggers, seteventmessage and check error
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
  view/question/question_card.php
Labels: Enhancement, 2

#873 #861 [Mod] add: rework mod num ref with ModeleNumRefSaturne
  core/modules/dolismq/answer/mod_answer_standard.php
  core/modules/dolismq/control/mod_control_standard.php
  core/modules/dolismq/controldet/mod_controldet_standard.php
  core/modules/dolismq/dolismqdocuments/controldocument/mod_controldocument_standard.php
  core/modules/dolismq/question/mod_question_standard.php
  core/modules/dolismq/sheet/mod_sheet_standard.php
  lib/dolismq.lib.php
Labels: Enhancement, 2

#870 #848 [Control] add: remove dolismq banner tab for use saturne
  view/control/control_card.php
Labels: Enhancement, 2

#869 #311 [Signature] add: control signature attendant page + workflow
  class/control.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
  lib/dolismq_control.lib.php
  view/control/control_card.php
Labels: Enhancement, 3

#881 #880 [Config] add: setup logo
  admin/about.php
  admin/control.php
  admin/documents.php
  admin/question.php
  admin/setup.php
  admin/sheet.php
Labels: Enhancement, 1

#866 #801 [Dashboard] add: DolismqDashboard for manage DoliSMQ dashboard
  class/control.class.php
  class/dolismqdashboard.class.php
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 3

#900 #877 [ODT] add: answer and fix include
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/dolismq/dolismqdocuments/controldocument/mod_controldocument_standard.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
Labels: Enhancement, 2, ODT / PDF

#902 #898 [Control] fix: missing getNomUrl on box
  core/boxes/dolismqwidget1.php
Labels: Bug, 1

#905 #903 [Control] fix: fatal with $object->linkedObjects cause "dolibarr name"
  class/control.class.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/modDoliSMQ.class.php
  core/tpl/dolismq_control_list.tpl.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  view/control/control_card.php
  view/control/control_list.php
Labels: Bug, 2

#906 #904 [Mod] fix: need value instead of global value
  core/modules/modDoliSMQ.class.php
Labels: Bug, 1

#907 #859 [Control] fix: need reset answer counter for action setValidated
  view/control/control_card.php
Labels: Bug, 1

#909 #847 #890 [CSS] add: answer buttons looks better on the phone
  class/actions_dolismq.class.php
  core/modules/modDoliSMQ.class.php
  css/dolismq.min.css
  css/scss/page/_control.scss
  view/control/control_card.php
Labels: Enhancement, 2, IHM

#901 #768 [Control] add: use select array instead of dolismq_select_product_lots
  view/control/control_card.php
Labels: Enhancement, 2

#910 #865 [Control] fix: missing check on maxPhoto
  js/dolismq.min.js
  js/modules/control.js
  view/control/control_card.php
Labels: Bug, 3, JS

#936 #935 [SQL] fix: move file control_attendants_role on root for insert data after create table
  sql/llx_c_control_attendants_role.sql
Labels: Bug, 1, Data model

#940 #860 [Control] fix: remove picto help confirm validated
  view/control/control_card.php
Labels: Enhancement, 1
