Repository Evarisk/digiquali, pull requests merged in 2023-06, with the labels that each got.

#1160 #1155 [CSS] add: minify menu_scss
  core/modules/modDoliSMQ.class.php
  css/scss/modules/_menu.min.css
Labels: 0, IHM

#1150 #1149 [ODT] fix: bug generation pdf due to ASCII characters
  langs/fr_FR/dolismq.lang
Labels: Bug, 1

#1173 #1161 [Cards] add: wpeo-button class to avoid spam create or add
  view/control/control_card.php
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 1

#1180 #1178 [AdminConf] fix: fatal sheet const array
  admin/sheet.php
Labels: Bug, 0

#1174 #1170 [Document] fix: strip html tags from question description
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 1

#1179 #1096 [Question] add: clone answers when cloning question
  class/question.class.php
Labels: Bug, 1

#1192 #1151 [Trad] fix: change trad
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 0

#1183 #1181 [Question/Sheet] fix: getpost on description and fields if error
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 0

#1196 #1195 [Control] fix: error check categories on box
  view/control/control_list.php
Labels: Bug, 1

#1202 #1197 [ODT] fix: missing ODT trad companies
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 0

#1129 #1124 [Mod] fix: fatal events button card
  view/control/control_card.php
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 1

#1131 #1130 [PublicControl] fix: missing '.php' in path url
  class/control.class.php
  core/modules/modDoliSMQ.class.php
  view/control/control_card.php
Labels: Bug, 1

#1123 #1122 [Control] fix: check good array and !empty
  view/control/control_card.php
Labels: Bug, 1

#1117 #1090 [Admin] fix: sheet const config array
  admin/sheet.php
  class/actions_dolismq.class.php
Labels: Bug, 0

#1114 #1059 [Mod] add: create button tags
  view/control/control_card.php
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 1

#1113 #1102 [Control] fix: fatal on search action in objectLinked list
  class/control.class.php
  core/tpl/dolismq_control_list.tpl.php
Labels: Bug, 2

#1112 #1095 [Question] fix: getpost question type on error
  view/question/question_card.php
Labels: Bug, 1

#1110 #1099 [Sheet] fix: ihm by removing td tag
  view/sheet/sheet_card.php
Labels: 0, IHM

#1115 #1089 [Public] add: warning qcFrequencyArray and move table cell
  public/control/public_control.php
  view/control/control_card.php
Labels: Enhancement, 2

#1193 #1133 [Control] add: status field in control_list
  view/control/control_list.php
Labels: Enhancement, 1

#1135 #48 [Triggers] add: improve triggers
  admin/setup.php
  class/control.class.php
  core/modules/modDoliSMQ.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 3

#1164 #1163 [Document] fix: missing lib cause fatal in public interface con…
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 1

#996 #727 [Control] add: equipment control and DLUO DDM
  admin/control.php
  class/control.class.php
  core/modules/dolismq/controlequipment/index.php
  core/modules/dolismq/controlequipment/mod_control_equipment_standard.php
  core/modules/modDoliSMQ.class.php
  langs/fr_FR/dolismq.lang
  lib/dolismq_control.lib.php
  sql/control/llx_control_equipment.key.sql
  sql/control/llx_control_equipment.sql
  view/control/control_card.php
  view/control/control_equipment.php
  view/control/control_medias.php
Labels: Enhancement, 5

#1206 #488 [Mod] add: 6 new dolibarr object linkable to control
  class/dolibarrobject.class.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/modDoliSMQ.class.php
  langs/fr_FR/dolismq.lang
  lib/dolismq_sheet.lib.php
  view/control/control_card.php
  view/control/control_list.php
Labels: Enhancement, 3

#1224 #1222 [SQL] fix: cant add default value on text so varchar it is
  class/sheet.class.php
  sql/sheet/llx_dolismq_sheet.sql
  sql/update.sql
Labels: Bug, 0, Data model

#1227 #1220 [Class] add: define typed properties to null or fatal
  class/control.class.php
Labels: Bug, 1

#1229 #1128 [Triggers] add: check if empty before foreach
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
Labels: Bug, 1

#1242 #1240 [Control] add: remove unused confirm_delete action
  view/control/control_card.php
Labels: Enhancement, 1

#1244 #1177 [JS] fix: rebuild js
  js/dolismq.min.js
Labels: Enhancement, 0

#1245 #1191 [Sheet] fix: rename sheet into control model
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 0

#1246 #1141 [Control] fix: control equipment object instanciation
  view/control/control_card.php
Labels: Enhancement, 0

#1247 #803 [ControlEquipment] add: equipment on odt
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  view/control/control_equipment.php
Labels: Enhancement, 3, ODT / PDF

#1254 #1253 [Class] fix: remove fatal typage
  class/dolibarrobject.class.php
Labels: Bug, 0

#1134 #764 [Tools] add: import and export dolismq sheet, questions and answer json
  class/answer.class.php
  class/question.class.php
  class/sheet.class.php
  core/modules/modDoliSMQ.class.php
  langs/fr_FR/dolismq.lang
  view/dolismqtools.php
Labels: Enhancement, 5
