Repository Evarisk/digiquali, pull requests merged in 2023-05, with the labels that each got.

#956 #946 [Control] fix: max photo on saturne_show_medias_linked
  view/control/control_card.php
Labels: Enhancement, 0

#953 #949 [Mod] add: remove unused files
  img/creativecommons/cc-by-sa_icon.png
  lib/dolismq_function.lib.php
  shell/pull/update_version.sh
Labels: Enhancement, 1

#939 #916 [Control] add: clone options for attendants and photos
  class/control.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  css/dolismq.min.css
  css/scss/page/_control.scss
  view/control/control_card.php
Labels: Enhancement, 2

#938 #917 [Control] add: generation ODT public interface
  admin/documents.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/modDoliSMQ.class.php
  documents/temp/index.php
  view/control/control_card.php
Labels: Enhancement, 2

#960 #959 [Mod] fix: remove include
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/dolismq/dolismqdocuments/controldocument/modules_controldocument.php
  core/tpl/dolismq_control_list.tpl.php
  view/control/control_card.php
  view/control/control_medias.php
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 1

#952 #947 [Control] fix: dashboard performance issue due to load fetchObjectLinked
  class/control.class.php
Labels: Enhancement, 2

#969 #967 [ODT] fix: missing trad ODT
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Enhancement, 0

#976 #975 [Mod] add: missing files index
  core/modules/dolismq/answer/index.php
  core/modules/dolismq/modules_dolismq.php
  sql/answer/index.php
Labels: Enhancement, 0

#982 #978 [ODT] fix: camelCase
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Enhancement, 0

#986 #985 [Trad] add: name ODT
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 0, Translation

#989 #988 [Class] add: use ControlDocument class for ODT generation
  lib/dolismq_control.lib.php
  view/control/control_card.php
Labels: Enhancement, 1

#987 #984 [Question] add: cancel button when editing answer
  view/question/question_card.php
Labels: Enhancement, 2

#1011 #1000 [Control] add: send email function with doc
  view/control/control_card.php
Labels: Enhancement, 1

#1010 #1003 [Trad] fix: remove unused trad
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 1

#1031 #1015 [Question] add: don't add answer for type 'OkKo' && 'OkKoToFixNonApplicable'
  view/question/question_card.php
Labels: Enhancement, 1

#1023 #1018 [Control] fix: set default value for arrayNbControlByVerdict dashboard
  class/control.class.php
Labels: Enhancement, 1

#1004 #997 [Control] fix: if no tag then return an empty tag message
  view/control/control_card.php
Labels: Bug, 1

#1025 #1013 [Control] fix: transform control answer ihm like comment
  css/dolismq.min.css
  css/scss/page/_control.scss
  view/control/control_card.php
Labels: Enhancement, 1, IHM

#1042 #1040 [Control] add: control list name
  core/tpl/dolismq_control_list.tpl.php
  view/control/control_list.php
Labels: Enhancement, 1

#1032 #1030 [Sheet] add: change trad for use same
  view/sheet/sheet_card.php
Labels: Enhancement, 0

#1033 #1029 [Control] add: delete signature with reopen action
  class/control.class.php
  langs/fr_FR/dolismq.lang
  view/control/control_card.php
Labels: Enhancement, 1

#1039 #1037 [SQL] add: missing Answer SQL key
  sql/answer/llx_dolismq_answer.key.sql
Labels: Enhancement, 1

#1065 #1052 [Widget] fix: fetch object linked to show boxes
  core/boxes/dolismqwidget1.php
  view/control/control_list.php
Labels: Bug, 1

#1067 #1055 [Control] fix: check if picto empty instead of different than 0
  view/control/control_card.php
Labels: Bug, 0

#1068 #1063 [SQL] fix: backward compatibility question type
  sql/update.sql
Labels: Bug, 2

#1071 #1054 [Question] add: remove action on question type OkKo/OkKoToFixNonApplicable
  view/question/question_card.php
Labels: Enhancement, 1

#1047 #1038 [Sheet] add: when error create, getpost linked_objects and desc
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1087 #773 [Mod] add: qc_frequency extrafields
  core/modules/modDoliSMQ.class.php
Labels: Enhancement, 2

#1020 #289 [Sheet] add: mandatory questions on sheet
  class/sheet.class.php
  langs/fr_FR/dolismq.lang
  sql/sheet/llx_dolismq_sheet.sql
  sql/update.sql
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 3, Data model

#1073 #643 [Public] add: public control interface view object info
  class/actions_dolismq.class.php
  class/control.class.php
  core/modules/modDoliSMQ.class.php
  langs/fr_FR/dolismq.lang
  public/control/index.php
  public/control/public_control.php
  sql/control/llx_dolismq_control.sql
  sql/update.sql
  view/control/control_card.php
Labels: Enhancement, 8

#1074 Generic objects links
  admin/sheet.php
  class/control.class.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/modDoliSMQ.class.php
  core/tpl/dolismq_control_list.tpl.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  js/dolismq.min.js
  js/modules/control.js
  langs/fr_FR/dolismq.lang
  lib/dolismq_sheet.lib.php
  view/control/control_card.php
  view/control/control_list.php
  view/sheet/sheet_card.php
Labels: Enhancement, 8

#1081 #666 [Control] add: nextControlDate info + rework link
  view/control/control_card.php
Labels: Enhancement, 2

#1085 #444 [Sheet] add: default tag on edit and creation
  admin/sheet.php
  core/modules/modDoliSMQ.class.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1080 #950 [Mod] add: implementation saturne functionnality
  admin/documents.php
  class/actions_dolismq.class.php
  class/answer.class.php
  class/control.class.php
  class/question.class.php
  class/sheet.class.php
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/modDoliSMQ.class.php
  langs/fr_FR/dolismq.lang
  lib/dolismq.lib.php
  lib/dolismq_control.lib.php
  lib/dolismq_question.lib.php
  lib/dolismq_sheet.lib.php
  view/control/control_card.php
  view/question/question_card.php
Labels: Enhancement, 5

#1105 #950 [Class] fix: mandatory_questions need initialized
  class/sheet.class.php
Labels: Bug, 1

#1092 #1091 [Mod] fix: missing answer on question with preset type OkKoToFixNonApplicable
  class/answer.class.php
  core/modules/modDoliSMQ.class.php
Labels: Bug, 3

#1166 #1165 [Sheet] fix: sheet needs context, hook shouldn't always return 1
  admin/sheet.php
  class/actions_dolismq.class.php
Labels: Bug, 2
