Repository Evarisk/digiquali, pull requests merged in 2023-09, with the labels that each got.

#1528 #1523 [IHM] add: use picto in tabmenu on phone
  lib/digiquali.lib.php
  lib/digiquali_control.lib.php
  lib/digiquali_sheet.lib.php
Labels: Enhancement, 1, IHM

#1531 #1530 [Triggers] fix: moved trigger tab translation to saturne
  admin/setup.php
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 0

#1534 #1529 [IHM] add: picto unlock
  view/control/control_card.php
Labels: Enhancement, 1, IHM

#1538 #1537 [View] fix: fatal banner actions
  class/control.class.php
  view/control/control_card.php
  view/control/control_equipment.php
  view/control/control_medias.php
Labels: Bug, 1

#1552 #1548 [Hook] fix: preg_match syntax
  class/actions_digiquali.class.php
Labels: Bug, 1

#1535 #1527 [Control] add: user conf ShowOnlyQuestionsWithNoAnswer
  core/tpl/digiquali_control_answers.tpl.php
  js/digiquali.min.js
  js/modules/control.js
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 1

#1548 #1545 [Control] add: CSS verdict button
  view/control/control_card.php
Labels: Enhancement, 1

#1549 #1540 [Control] add: auto save action question answer
  admin/control.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_control_answers.tpl.php
  core/tpl/digiquali_control_answers_save_action.tpl.php
  core/tpl/digiquali_public_control.tpl.php
  js/digiquali.min.js
  js/modules/control.js
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 2

#1554 #1553 [Core] add: new version number 1.9.0
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0
