Repository Evarisk/digiquali, pull requests merged in 2023-07, with the labels that each got.

#1072 [Control] add: control reminder functionnality
  admin/control.php
  admin/setup.php
  class/control.class.php
  core/modules/modDoliSMQ.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 5

#1119 #879 [Dashboard] add: control date dashboard
  class/control.class.php
  css/dolismq.min.css
  css/scss/element/_dashbord-control.scss
  css/scss/element/_element.scss
  css/scss/variable/_colors.scss
  langs/fr_FR/dolismq.lang
  package-lock.json
Labels: Enhancement, 3

#1257 #1256 [Question] fix: check type to avoid answer multiplication
  view/question/question_card.php
Labels: Bug, 0

#1261 #1260 [Import] fix: file name check
  view/dolismqtools.php
Labels: Enhancement, 1

#1268 #1267 [Control] fix: show no verdict as N/A
  class/control.class.php
  core/tpl/dolismq_control_list.tpl.php
Labels: Enhancement, 2

#1277 #1276 [ControlEquipment] add: number of equipment in control header
  lib/dolismq_control.lib.php
  view/control/control_equipment.php
Labels: Enhancement, 1

#1283 #1281 [Control] fix: fields position in list
  view/control/control_list.php
Labels: Enhancement, 1

#1285 #1278 [Sheet] fix: mandatory controllable object
  langs/fr_FR/dolismq.lang
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1286 #1279 [Control] fix: answers saving
  js/dolismq.min.js
  js/modules/control.js
  view/control/control_card.php
Labels: Enhancement, 3

#1282 #1280 [Control] fix: remove duplicate of confirm_archive action
  view/control/control_card.php
Labels: Bug

#1275 #1274 [Control] add: missing product object
  view/control/control_card.php
Labels: Bug, 0

#1298 #1290 [Translation] fix: conf translation & spacing
  langs/fr_FR/dolismq.lang
Labels: 1, Translation

#1255 #1241 [Tools] add: mandatory question to export import
  class/sheet.class.php
  view/dolismqtools.php
Labels: Enhancement, 0

#1273 #1271 [Documents] fix: if no equipment, display no data on doc
  core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, Enhancement, 1

#1293 #1264 #1291 [Control] add: remove trad NoVerdict and picto dashboard
  class/control.class.php
  langs/fr_FR/dolismq.lang
  public/control/public_control.php
Labels: Enhancement, 1

#1294 #1265 [Control] fix: disable signature if there is no verdict
  view/control/control_card.php
Labels: Enhancement, 1

#1304 fix control list
  class/control.class.php
  langs/fr_FR/dolismq.lang
  view/control/control_list.php
Labels: Enhancement, 2

#1305 #1300 [Control] add: setDraft method and remove setValidated
  class/control.class.php
  view/control/control_card.php
Labels: Enhancement, 1

#1308 #1307 [Triggers] add: generate Document Triggers
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 1

#1312 #1311 [Trad] fix: missing trad new linked objects
  langs/fr_FR/dolismq.lang
Labels: Enhancement, 0

#1314 #1313 [Card] add: use single hidden input instead for manage modal options
  view/control/control_card.php
  view/question/question_card.php
Labels: Enhancement, 2

#1316 #1315 [Control] add: use saturne TPL builddoc action
  view/control/control_card.php
Labels: Enhancement, 1

#1318 #1317 [Sheet] fix: remove SheetLinked use
  class/control.class.php
  langs/fr_FR/dolismq.lang
  view/control/control_card.php
Labels: Enhancement, 0

#1325 #1324 [Sheet] fix: set event message proc
  view/sheet/sheet_card.php
Labels: Enhancement, 0

#1326 #1322 #1323 [Control] fix: change visibility and position control fields
  class/control.class.php
Labels: Bug, 1

#1319 #1252 [Triggers] fix: trigger description
  class/answer.class.php
  class/control.class.php
  class/question.class.php
  class/sheet.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
Labels: Enhancement, 3

#1272 #1270 [Answer] add: const status and filter fetchall with status
  class/answer.class.php
  view/control/control_card.php
  view/question/question_card.php
Labels: Bug, 1

#1329 #1328 [Triggers] fix: delete duplicate code
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
Labels: Bug, 0

#1341 #1337 [Control] fix: list css
  core/tpl/dolismq_control_list.tpl.php
Labels: Enhancement, 0

#1342 #1336 [Control] fix: controlled object type
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
Labels: Enhancement, 1

#1343 #1334 [Dashboard] add: get controls with self::STATUS_LOCKED
  class/control.class.php
Labels: Enhancement, 0

#1347 #1330 [Control] add: move next control date functionnality on trigger lock
  class/control.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
Labels: Enhancement, 1

#1344 #1131 [Tools] add: ref_ext and import_key when import
  view/dolismqtools.php
Labels: Enhancement, 1

#1345 #1335 [ControlEquipment] add: no equipment linked inside table
  class/control.class.php
  view/control/control_equipment.php
Labels: Bug, 1

#1352 #1351 [Control] fix: remove remainder code
  view/control/control_card.php
Labels: Enhancement, 0

#1356 #1354 [Control] fix: control date interactions with card & reminders
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
  view/control/control_card.php
Labels: Enhancement, 1

#1249 #1248 [Mod] add: new version number 1.7.0
  README.md
  core/modules/modDoliSMQ.class.php
  core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php
Labels: Enhancement, 0

#1295 #1287 [Control] fix: public interface php
  view/control/control_card.php
Labels: Enhancement, 1

#1381 #1363 [Core] add: editor config file
  .editorconfig
Labels: Enhancement, 0

#1372 #1365 [Control] fix: rename ControlDate into CreationDate
  class/control.class.php
Labels: Enhancement, 0

#1373 #1366 [Control] fix: object post retrieval
  class/control.class.php
  view/control/control_card.php
Labels: Enhancement, 1

#1371 #1367 [Sheet] fix: translation
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 0

#1378 #1361 [Control] add: public control answers filling
  admin/control.php
  class/actions_digiquali.class.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_control_answers.tpl.php
  core/tpl/digiquali_control_answers_save_action.tpl.php
  langs/fr_FR/digiquali.lang
  public/control/public_control.php
  public/control/public_survey.php
  view/control/control_card.php
Labels: Enhancement, 3

#1390 #1384 [Sheet] fix: require saturne task for linkable objects
  lib/digiquali_sheet.lib.php
Labels: Enhancement, 0

#1391 #1383 [Class] fix: split dolibarr objects in separate classes
  class/dolibarrobjects/digiqualiexpedition.class.php
  class/dolibarrobjects/digiqualisupplierproposal.class.php
  lib/digiquali_sheet.lib.php
Labels: Enhancement, 1

#1394 #1389 [Core] fix: set directories rights for rename
  core/modules/modDigiQuali.class.php
Labels: Bug, 2

#1369 #1362 [Core] fix: require category class in mod
  class/answer.class.php
  core/modules/modDigiQuali.class.php
Labels: Enhancement, 1

#1392 #1387 [Control] fix: default text answer value
  core/tpl/digiquali_control_answers.tpl.php
  core/tpl/digiquali_control_list.tpl.php
Labels: Bug, 1

#1374 #1364 [Control] add: public interface url copy to clipboard action
  js/digiquali.min.js
  js/dolismq.min.js
  js/modules/control.js
  view/control/control_card.php
Labels: Enhancement, 2

#1399 #1396 [SQL] fix: update module name in database
  sql/update.sql
Labels: Enhancement, 2

#1402 fix public survey page
  core/tpl/digiquali_control_answers_save_action.tpl.php
  public/control/public_survey.php
Labels: Enhancement, 0

#1386 #1385 [Core] fix: remove standard requires and replace it with saturnes
  class/answer.class.php
  class/control.class.php
  class/dolibarrobject.class.php
  class/question.class.php
  class/sheet.class.php
  view/control/control_card.php
  view/control/control_equipment.php
  view/digiqualitools.php
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1413 #1411 [Triggers] fix: fatal error caused by external modules
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Bug, 1

#1420 #1419 [Control] fix: fatal error on validation
  view/control/control_card.php
Labels: Bug, 1

#1422 #1421 [Control] fix: fatal error on control equipment page
  view/control/control_equipment.php
Labels: Bug, 2

#1424 #1423 [Control] fix: control equipment expiration date in odt
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 2

#1425 #1415 [Control] fix: strip tags in control equipment description
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Enhancement, 1

#1427 #1418 [Control] fix: action lock
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Bug, 2

#1428 #1426 [Translation] add: control verdict trigger
  langs/fr_FR/digiquali.lang
Labels: 0, Translation

#1429 fix rework control equipment
  class/control.class.php
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  js/digiquali.min.js
  js/modules/control.js
  langs/fr_FR/digiquali.lang
  sql/control/llx_digiquali_control_equipment.sql
  sql/update.sql
  view/control/control_equipment.php
Labels: Enhancement, 3
