Repository Evarisk/digiquali, pull requests merged in 2023-12, with the labels that each got.

#1581 #1580 [Document] fix: change fillTagLines function according to saturne
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 1

#1597 #1593 [Control] fix: progress bar
  view/control/control_card.php
Labels: Bug, 1

#1355 #1353 [Hook] fix: Hook name
  class/actions_digiquali.class.php
Labels: Bug, 0

#1604 #836 [Sheet] fix: improve sheet card view question list
  view/sheet/sheet_card.php
Labels: Bug, 1

#1606 #1577 #1600 [Control] fix: missing element to reload in JS control
  js/digiquali.min.js
  js/modules/control.js
Labels: Bug, 2, JS

#1610 #1609 [Mod] fix: remove modAgenda dependancies
  core/modules/modDigiQuali.class.php
Labels: Bug, 0

#1608 #1607 [Hook] fix: remove category hook now in saturne
  class/actions_digiquali.class.php
Labels: Enhancement, 0

#1616 #1560 #1562 [Control] fix: edit control date
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  view/control/control_card.php
Labels: Bug, 2

#1618 #1617 [Mod] add: new version number 1.9.1
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0

#1642 #1633 [ODT] fix: DoliSMQ issue
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
Labels: Bug, 0, ODT / PDF

#1641 #1640 [Control] add: improve IHM control and signatory infos
  core/tpl/digiquali_control_list.tpl.php
  view/control/control_list.php
Labels: Enhancement, 3, IHM
