Repository Evarisk/digiquali, pull requests merged in 2024-01, with the labels that each got.

#1643 #1639 [Card] fix: get categories selected on edit action
  view/question/question_card.php
  view/sheet/sheet_card.php
Labels: Bug, 1

#1645 #1638 [List] add: improve search status and rename status enabled
  class/question.class.php
  class/sheet.class.php
  langs/fr_FR/digiquali.lang
  view/question/question_list.php
  view/sheet/sheet_list.php
Labels: Enhancement, 2

#1646 #1637 [List] add: mass action archive
  core/tpl/digiquali_control_list.tpl.php
  view/control/control_list.php
  view/question/question_list.php
  view/sheet/sheet_list.php
Labels: Enhancement, 2

#1656 #1655 [PublicSurvey] fix: error SQL missing user info
  public/control/public_survey.php
Labels: Bug, 1

#1625 #1623 [ODT] add: improve questions table, remove useless text
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 1, ODT / PDF

#1654 #882 [Control] add: average and threshold
  class/control.class.php
  class/sheet.class.php
  core/tpl/digiquali_control_answers.tpl.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  sql/control/llx_digiquali_control.sql
  sql/sheet/llx_digiquali_sheet.sql
  sql/update.sql
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 3

#1683 #1681 #1682 [Sheet] add: improve succes_rate field
  README.md
  class/control.class.php
  class/sheet.class.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_control_answers.tpl.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  langs/fr_FR/digiquali.lang
  sql/control/llx_digiquali_control.sql
  sql/sheet/llx_digiquali_sheet.sql
  sql/update.sql
  view/control/control_card.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1659 #1657 [SQL] add: data model survey
  sql/data.sql
  sql/llx_c_survey_attendants_role.sql
  sql/survey/index.php
  sql/survey/llx_categorie_survey.key.sql
  sql/survey/llx_categorie_survey.sql
  sql/survey/llx_digiquali_survey.key.sql
  sql/survey/llx_digiquali_survey.sql
  sql/survey/llx_digiquali_survey_extrafields.key.sql
  sql/survey/llx_digiquali_survey_extrafields.sql
  sql/survey/llx_digiquali_surveydet.key.sql
  sql/survey/llx_digiquali_surveydet.sql
  sql/survey/llx_digiquali_surveydet_extrafields.key.sql
  sql/survey/llx_digiquali_surveydet_extrafields.sql
Labels: Enhancement, 2, Data model

#1699 #1698 [JS/CSS] fix: regenerate min files
  css/digiquali.min.css
  js/digiquali.min.js
Labels: 0

#1691 #1687 [Trans] fix: traduction
  langs/fr_FR/digiquali.lang
  manifest.json.php
Labels: 0, Translation

#1702 #1688 [Control] add: warning if no categories generated on image view
  admin/sheet.php
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Bug, 1

#1704 #1669 [PublicSurvey] add: public survey page
  langs/fr_FR/digiquali.lang
  public/survey/index.php
  public/survey/public_survey.php
Labels: Enhancement, 1

#1707 #1706 [Sheet] fix: status field search doesn't work
  view/sheet/sheet_list.php
Labels: Bug, 1

#1705 #1690 [Survey] add: success_rate field
  class/survey.class.php
  core/modules/digiquali/digiqualidocuments/surveydocument/doc_surveydocument_odt.modules.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  sql/survey/llx_digiquali_survey.sql
  sql/update.sql
  view/survey/survey_card.php
Labels: Enhancement, 1

#1710 #1709 [SQL] fix: sheet type not null and update empty value with control
  sql/sheet/llx_digiquali_sheet.sql
  sql/update.sql
Labels: 1, Data model

#1711 #1689 [ODT] fix: setAttendantsSegment function missing parameters
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 1, ODT / PDF

#1708 #1693 [Conf] fix: rework control configuration page
  admin/control.php
  admin/survey.php
  class/actions_digiquali.class.php
  core/modules/modDigiQuali.class.php
  langs/fr_FR/digiquali.lang
Labels: Bug, 1
