Repository Evarisk/digiquali, pull requests merged in 2024-02, with the labels that each got.

#1716 #1601 [Sheet] fix: error manage question position
  class/sheet.class.php
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/digiquali/digiqualidocuments/surveydocument/doc_surveydocument_odt.modules.php
  core/tpl/digiquali_answers_save_action.tpl.php
  public/public_answer.php
  view/control/control_card.php
  view/digiqualitools.php
  view/sheet/sheet_card.php
  view/sheet/sheet_export.php
  view/sheet/sheet_list.php
  view/survey/survey_card.php
Labels: Bug, 3

#1731 #1730 [Public] fix: missing temp directory in documents
  documents/temp/index.php
Labels: Bug, 0

#1733 #1732 [Question] fix: button picto dropdown content
  lib/digiquali_answer.lib.php
Labels: Enhancement, 0

#1718 #1717 [Lib] fix: remove object type
  core/substitutions/functions_digiquali.lib.php
Labels: Bug, 0

#1743 #1740 [Card] fix: remove bug tags on card for mobile version
  view/control/control_card.php
  view/question/question_card.php
  view/sheet/sheet_card.php
  view/survey/survey_card.php
Labels: Bug, 2

#1738 #1737 [Control] fix: clean show view
  view/control/control_card.php
  view/survey/survey_card.php
Labels: Enhancement, 1

#1728 #1725 [Control] add: track_id in control list
  class/control.class.php
  class/survey.class.php
Labels: Enhancement, 1

#1747 Fix equipment control
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Bug, 1
