Repository Evarisk/digiquali, pull requests merged in 2024-08, with the labels that each got.

#1858 #1805 #1853 [Sheet] fix: updateQuestionsPosition
  class/sheet.class.php
  view/digiqualitools.php
  view/question/question_list.php
  view/sheet/sheet_card.php
  view/sheet/sheet_export.php
Labels: Bug, 2

#1836 #1824 [ODT] add: odt life sheet for product and lot/serial control
  documents/doctemplates/lifesheetlotserialdocument/template_lotserialdocument.odt
  documents/doctemplates/lifesheetlotserialdocument/template_lotserialdocument_medias.odt
Labels: Enhancement, 2, ODT / PDF

#1863 #1820 [Sheet] add: import sheet/question with status validated
  view/digiqualitools.php
  view/sheet/sheet_card.php
  view/sheet/sheet_export.php
Labels: Enhancement, 2

#1778 #1761 [Control] add: if create fromtype then filter model list
  view/control/control_card.php
Labels: Enhancement, 1

#1841 #1840 [Card] add: lib Hammer JS
  public/public_answer.php
  view/control/control_card.php
  view/question/question_card.php
  view/sheet/sheet_card.php
  view/survey/survey_card.php
Labels: Enhancement, 1

#1750 #1719 [List] add: last dates and answer/question on control and survey
  core/tpl/digiquali_control_list.tpl.php
  core/tpl/digiquali_survey_list.tpl.php
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 3

#1804 #1788 [Question] add: description field on question list
  class/question.class.php
  view/question/question_list.php
Labels: Enhancement, 2

#1874 #1873 [Mod] add: new version
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0

#1876 #1875 [Survey] fix: fatal error, missing require action
  admin/sheet.php
  view/survey/survey_card.php
Labels: Bug, 2

#1878 #1877 [Tools] add: wpeo-button to avoid spam click
  view/digiqualitools.php
Labels: Bug, 0
