Repository Evarisk/digiquali, pull requests merged in 2024-03, with the labels that each got.

#1727 #1723 [Public] fix: invert model and control getnomurl
  core/tpl/digiquali_public_control.tpl.php
  langs/fr_FR/digiquali.lang
Labels: Question, 1, IHM

#1745 #1744 [Hook] fix: do not display control history link in vue create
  core/modules/modDigiQuali.class.php
Labels: Bug, 1

#1754 #1753 [Module] fix: remove useless file
  core/modules/digiquali/digiqualidocuments/controldocument/modules_controldocument.php
  core/modules/digiquali/digiqualidocuments/surveydocument/modules_surveydocument.php
Labels: Enhancement, 0

#1757 #1756 [Hook] fix: fatal typage formObjectOptions
  class/actions_digiquali.class.php
Labels: Bug, 1

#1758 #1714 [PublicAnswer] add: signatory
  admin/publicinterface.php
  class/actions_digiquali.class.php
  core/tpl/digiquali_answers_save_action.tpl.php
  public/control/public_control.php
  public/control/public_control_history.php
  public/public_answer.php
  public/survey/public_survey.php
  view/control/control_card.php
  view/survey/survey_card.php
Labels: Enhancement, 8

#1752 #1751 [Mod] add: new version number 1.11.0
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0

#1772 #1771 [Class] fix: do not type fk_user_creat and fk_user_modif
  class/answer.class.php
  class/control.class.php
  class/question.class.php
  class/sheet.class.php
  class/survey.class.php
Labels: Bug, 0
