Repository Evarisk/digiquali, pull requests merged in 2024-06, with the labels that each got.

#1800 #1798 [Sheet] fix: add reposition class to sheet card
  view/sheet/sheet_card.php
Labels: Bug, Good first issue, 2

#1808 #1806 [sheet] fix: use current date for creation and tms when cloning
  class/sheet.class.php
Labels: Bug, Good first issue, 0

#1814 #1813 [Mod] add: new version number
  README.md
  core/modules/modDigiQuali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 0

#1835 #1834 [Class] fix: remove type for $isextrafieldmanaged
  class/answer.class.php
  class/control.class.php
  class/question.class.php
  class/sheet.class.php
  class/survey.class.php
Labels: Bug, 0
