Repository Evarisk/digiquali, pull requests merged in 2024-07, with the labels that each got.

#1837 #1823 [Manifest] add: domain name to pwa name
  manifest.json.php
Labels: Enhancement, 1

#1773 #1769 [Export] fix: replace name by sheet label or something more human
  view/digiqualitools.php
  view/sheet/sheet_export.php
Labels: Enhancement, 0

#1748 #1721 [Control] add: label and copy label on create from sheet
  class/control.class.php
  sql/control/llx_digiquali_control.sql
  sql/update.sql
  view/control/control_card.php
Labels: Enhancement, 2

#1822 #1821 [ControlCard] fix: check array not empty before using
  view/control/control_card.php
Labels: Bug, 0

#1829 #1828 [Trad] add: update QcFrequency
  langs/fr_FR/digiquali.lang
Labels: 0, Translation

#1797 #1736 [Question] add: mass add of question into a sheet
  langs/fr_FR/digiquali.lang
  view/question/question_list.php
  view/sheet/sheet_card.php
Labels: Enhancement, 2

#1859 #1857 [PublicAnswer] fix: saturne_show_medias_linked usesharelink at 1
  core/tpl/digiquali_answers.tpl.php
Labels: Bug, 0, Demo
