Repository Evarisk/digiquali, pull requests merged in 2025-07, with the labels that each got.

#2161 Fix Import/Export functionality
  class/sheet.class.php
  view/digiqualitools.php
  view/sheet/sheet_export.php
Labels: Enhancement, 1

#2134 Fix questions groups 2
  class/question.class.php
  class/sheet.class.php
  core/tpl/digiquali_answers.tpl.php
  core/tpl/digiquali_question_single.tpl.php
  core/tpl/frontend/digiquali_answers_frontend.tpl.php
  css/digiquali.min.css
  css/scss/page/_sheet-tree.scss
  css/scss/page/_sheet.scss
  js/digiquali.min.js
  js/modules/object.js
  js/modules/sheet.js
  langs/fr_FR/digiquali.lang
  lib/digiquali_answer.lib.php
  public/public_answer.php
  view/digiqualitools.php
  view/questiongroup/questiongroup_card.php
  view/sheet/sheet_card.php
Labels: Bug, 2

#2133 #2126 [Control] fix: translation to accomodate lock confirm box
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 1

#2186 Use textarea for Question Comments Instead of Single-Line Input
  core/tpl/digiquali_question_single.tpl.php
Labels: 2

#2166 Enhance Grouped Question Order
  class/questiongroup.class.php
Labels: Enhancement, 1

#2187 #2175 [SurveyClass] add: generate id for survey from clone
  class/control.class.php
  class/survey.class.php
Labels: Bug, 0

#2209 #2207 [QuestionSingleTpl] fix: answered question not blue in the list
  core/tpl/digiquali_question_single.tpl.php
Labels: Enhancement, 1
