Repository Evarisk/digiquali, pull requests merged in 2025-05, with the labels that each got.

#2093 #2058 [Control] add: text to see next control on locking screen
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 1

#2095 #2057 [control] add: automatisation on name with date and label of product
  view/control/control_card.php
Labels: Enhancement, 1

#2077 #1902 [ODT] add odt landscape surveydocument
  documents/doctemplates/controldocument/template_controldocument_photo_landscape_actions.odt
  documents/doctemplates/surveydocument/template_surveydocument-paysage.odt
Labels: 2

#1894 #1572 [odt] add odt controle file with good and not good medias
  documents/doctemplates/controldocument/template_controldocument_withgood-notgood-medias.odt
Labels: Enhancement, 1, ODT / PDF

#2092 Fix Postgresql compatibility
  class/actions_digiquali.class.php
  class/sheet.class.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_control_list.tpl.php
  core/tpl/digiquali_survey_list.tpl.php
  sql/data.sql
  sql/update.sql
  view/control/control_card.php
  view/control/control_equipment.php
  view/survey/survey_card.php
Labels: Bug, 2

#2103 Add sheet questions statistics
  class/sheet.class.php
  css/digiquali.min.css
  css/scss/page/_sheet-stats.scss
  css/scss/page/answer/_answer.scss
  css/scss/style.scss
  langs/fr_FR/digiquali.lang
  lib/digiquali_sheet.lib.php
  view/sheet/sheet_stats.php
Labels: Enhancement, 5

#2132 #2120 [Trad] add: missing translations
  class/actions_digiquali.class.php
  langs/fr_FR/digiquali.lang
Labels: 1, Translation
