Repository Evarisk/digiquali, pull requests merged in 2025-04, with the labels that each got.

#2054 #2053 [List] add: list reworks
  README.md
  admin/sheet.php
  class/actions_digiquali.class.php
  class/control.class.php
  class/dolibarrobject.class.php
  class/dolibarrobjects/digiqualiexpedition.class.php
  class/dolibarrobjects/digiqualisupplierproposal.class.php
  class/question.class.php
  class/sheet.class.php
  class/survey.class.php
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
  core/modules/digiquali/digiqualidocuments/surveydocument/doc_surveydocument_odt.modules.php
  core/modules/modDigiQuali.class.php
  core/substitutions/functions_digiquali.lib.php
  core/tpl/digiquali_answers.tpl.php
  core/tpl/digiquali_answers_save_action.tpl.php
  core/tpl/digiquali_control_list.tpl.php
  core/tpl/digiquali_survey_list.tpl.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  digiquali.main.inc.php
  digiqualiindex.php
  langs/fr_FR/digiquali.lang
  lib/digiquali_answer.lib.php
  lib/digiquali_control.lib.php
  lib/digiquali_sheet.lib.php
  public/control/public_control_history.php
  sql/update.sql
  view/control/control_card.php
  view/control/control_list.php
  view/question/question_list.php
  view/sheet/sheet_card.php
  view/sheet/sheet_list.php
  view/survey/survey_card.php
  view/survey/survey_list.php
Labels: Enhancement, 8

#2072 #2071 [ODT] add: odt new design and project label information
  documents/doctemplates/controldocument/template_controldocument.odt
  documents/doctemplates/controldocument/template_controldocument_photo.odt
  documents/doctemplates/lifesheetlotserialdocument/template_lotserialdocument.odt
  documents/doctemplates/lifesheetlotserialdocument/template_lotserialdocument_medias.odt
Labels: 1

#2088 #2087 [Hook] fix: missing require on saturne_get_objects_metadata function
  class/actions_digiquali.class.php
Labels: Bug, 1

#2098 #2097 [Control] fix: repair sql filter for fromtype and more error management with fk_sheet
  view/control/control_card.php
Labels: Bug, 2
