Repository Evarisk/digiquali, pull requests merged in 2025-02, with the labels that each got.

#1970 #1967 [QuestionPercent] add: custom steps
  class/question.class.php
  js/digiquali.min.js
  js/modules/question.js
  langs/fr_FR/digiquali.lang
  lib/digiquali_answer.lib.php
  sql/question/llx_digiquali_question.sql
  sql/update.sql
  view/question/question_card.php
Labels: Enhancement, 2

#1968 #1957 [Questions / Trad] add : number on trad for list of questions
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
  view/sheet/sheet_card.php
  view/survey/survey_card.php
Labels: Enhancement, 1

#1982 #1981 [Control] fix: repair showInputField for dolibarr 20
  class/control.class.php
Labels: Bug, 5

#1991 #1929 [PublicControl] add: rework control public interface IHM and functionnality
  admin/control.php
  class/control.class.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_public_control.tpl.php
  core/tpl/frontend/control_documentation_frontend_view.tpl.php
  core/tpl/frontend/control_item_frontend_view.tpl.php
  core/tpl/frontend/linked_object_and_control_frontend_view.tpl.php
  css/digiquali.min.css
  css/scss/page/_page.scss
  css/scss/page/_public-control.scss
  js/digiquali.min.js
  js/modules/control.js
  langs/fr_FR/digiquali.lang
  lib/digiquali_control.lib.php
  public/control/public_control_history.php
Labels: Enhancement, 8

#1997 #1995 [Trad] fix: improve toggle text clarity for last control display option
  langs/fr_FR/digiquali.lang
Labels: 1, Translation

#1999 #1937 [Control] add: control equipment in clone controls options
  class/control.class.php
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 1

#1998 #1896 [ControlClass] add: default image from sheet on create
  class/control.class.php
Labels: Enhancement, 2

#1953 #1931 [ProductLotCard] fix: button link control history
  class/actions_digiquali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
  langs/fr_FR/digiquali.lang
Labels: Enhancement, 3, copac

#2003 #2001[QuestionCard] fix: checkbox reversed and photo not appear on error
  js/digiquali.min.js
  js/modules/question.js
  view/question/question_card.php
Labels: Bug, 2

#2000 #1988 [Control] fix: bad place for user config
  admin/control.php
  core/tpl/digiquali_answers.tpl.php
  js/digiquali.min.js
  js/modules/control.js
  langs/fr_FR/digiquali.lang
  view/control/control_card.php
Labels: Enhancement, 2

#2006 #2001 [Control] fix: round for improve nextControl calcul
  class/control.class.php
  core/tpl/digiquali_control_list.tpl.php
  lib/digiquali_control.lib.php
Labels: Bug, 2

#2007 #1994 [PublicControl] fix: management of external public interface
  class/actions_digiquali.class.php
  core/tpl/frontend/control_item_frontend_view.tpl.php
  core/tpl/frontend/linked_object_and_control_frontend_view.tpl.php
  css/digiquali.min.css
  css/scss/page/_public-control.scss
  langs/fr_FR/digiquali.lang
  lib/digiquali_control.lib.php
  public/control/public_control_history.php
  view/control/control_card.php
Labels: Enhancement, 3

#2013 #2012 [PublicControlHistory] add: user conf on public interface
  public/control/public_control_history.php
Labels: Bug, 0

#2014 #1993 [DigiqualiControl] add: link to object
  core/tpl/frontend/control_documentation_frontend_view.tpl.php
  lib/digiquali_control.lib.php
Labels: Enhancement, 1

#1969 #1960 [PercentQuestion] add: percent on top of input cursor
  css/digiquali.min.css
  css/scss/page/_public-answer.scss
  js/digiquali.min.js
  js/modules/object.js
  lib/digiquali_answer.lib.php
Labels: Enhancement, 3

#2016 #2009 [Hook] fix: backward extrafields options_control_history_link
  class/actions_digiquali.class.php
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Enhancement, 1

#2010 #2008 [PublicControl] fix: missing value for create button
  core/modules/modDigiQuali.class.php
  core/tpl/frontend/control_documentation_frontend_view.tpl.php
  core/tpl/frontend/control_item_frontend_view.tpl.php
  css/digiquali.min.css
  css/scss/page/_public-control.scss
  lib/digiquali_control.lib.php
  public/control/public_control_history.php
Labels: Enhancement, 2

#2032 #2025 [Triggers] fix: action reminders wrong info
  core/triggers/interface_99_modDigiQuali_DigiQualiTriggers.class.php
Labels: Bug, 1
