Repository Evarisk/digiquali, pull requests merged in 2025-08, with the labels that each got.

#2218 #2217 [ControlClass] add: displayAnswers function
  class/control.class.php
Labels: Bug, 1

#1904 #1903 [ODT] add: question accept html
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Enhancement, 0

#2229 #2228 [ODT] fix: bug on answers photo in odt
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 1

#2231 #2228 [ODT] fix: bug on answers photo in odt
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 2

#2233 #2233 [ODT /Thumb] fix : thumb on generation odt
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 2
