Repository Evarisk/digiquali, pull requests merged in 2025-01, with the labels that each got.

#1950 #1647 [Control] add: label on model and linked object
  view/control/control_card.php
Labels: Enhancement, 1

#1951 #1935 [Hooks] add: missing picto extrafields
  class/actions_digiquali.class.php
Labels: Enhancement, 1

#1908 #1907 [Dashboard] add: name on graph to remove it
  class/control.class.php
  class/survey.class.php
Labels: Enhancement, 1

#1870 #1779 [Control] fix: use JS to update modal content
  js/digiquali.min.js
  js/modules/object.js
Labels: Bug, 1

#1899 #1851 [Control] fix: img size in odt
  core/modules/digiquali/digiqualidocuments/controldocument/doc_controldocument_odt.modules.php
Labels: Bug, 3, ODT / PDF

#1942 #1928 [Cards] add: badge on controls
  class/actions_digiquali.class.php
  class/control.class.php
  class/sheet.class.php
Labels: Enhancement, 3

#1955 #1825 [Control] add: custom color for controls
  admin/control.php
  class/control.class.php
  core/modules/modDigiQuali.class.php
  core/tpl/digiquali_control_list.tpl.php
  core/tpl/digiquali_public_control.tpl.php
  langs/fr_FR/digiquali.lang
  public/control/public_control_history.php
Labels: Enhancement, 2

#1812 #1775 [PublicAnswer] add: rework IHM
  admin/publicinterface.php
  core/tpl/digiquali_answers.tpl.php
  core/tpl/frontend/digiquali_answers_frontend.tpl.php
  core/tpl/medias_answer_modal.tpl.php
  css/digiquali.min.css
  css/scss/page/_control.scss
  css/scss/page/_page.scss
  css/scss/page/_public-answer.scss
  css/scss/page/_question-answer.scss
  css/scss/style.scss
  css/scss/variable/_colors.scss
  js/digiquali.min.js
  js/modules/object.js
  langs/fr_FR/digiquali.lang
  lib/digiquali_answer.lib.php
  public/public_answer.php
  view/question/question_card.php
Labels: Enhancement, 5, IHM

#1963 #1961 [Trad] fix: spelling error
  langs/fr_FR/digiquali.lang
Labels: 0, Translation

#1964 #1958 [Card] fix: need rounding of 2 for question average
  view/control/control_card.php
  view/sheet/sheet_card.php
  view/survey/survey_card.php
Labels: Bug, 0
